dir() #Trás uma lista de métodos relativo ao escopo local
dir(100) #Trás uma lista de métodos relativo ao escopo da classe inteira
dir('s') #Trás uma lista de métodos relativos ao escopo da classe string
dir([]) #Trás uma lista de métodos relativos ao escopo da classe lista
help() #Trás a documentação relativa ao escopo local da aplicação
help(100) #Trás a documentação relatica ao escopo da classe inteira

#------------------------------------------------------------------#
##As funções dir e help funcionam offline, como forma para acesso de documentação e base de dados